sequenceDiagram
    autonumber
    actor U as User
    participant W as WearOS App
    participant M as Mobile App
    participant KC as Tenant System
    participant IO as Orchestrator
    participant PG as Postgres
    participant RD as Redis
    participant FCM as Firebase Cloud Messaging
    participant KF as Kafka Broker
    participant MA as Model API

    U->>KC: Open registration page
    KC->>IO: REST: {POST} createPairing

    IO-)PG: JDBC: SELECT app_user(userId, tenantId)
    alt user already exists 
        PG--)IO: JDBC: Response
        IO-->>KC: REST: Error: user already exists
        KC-->>U: Registration failed (user exists)
    else user doesn't exist yet
        PG--)IO: JDBC: Response
        IO->>RD: Create pairing(tenantId, userId, jti, status="CREATED", reason="FLOW_CREATED")
        IO->>KC: REST: PairingCreatedResponse(pairingId)
        KC-->>U: Show pairing QR code
        U->>M: Scan pairing QR code
        M->>IO: REST: {POST} initPairing
        IO->>RD: REDIS: Verify pairing exists(pairingId)
        alt pairing not found, expired or already initalized
            RD-->>IO: REDIS: NOT FOUND/EXPIRED
            IO-->>M: REST: Error: invalid pairing
            M-->>U: Pairing failed (invalid pairing)
        else pairing present
        IO->>RD: REDIS: Update pairing(pairingId, deviceInfo, status="PENDING", reason="FLOW_INITIALIZED_ON_MOBILE_DEVICE")
        IO-->>M: REST: PairingInitializedResponse(nonce, expiryTime)
        M->>W: DATALAYER: Request ECG measurement(challengeId)
        W->>U: Prompt: "Start ECG measurement"
        U-->>W: User performs ECG measurement
        W-->>M: DATALAYER: ECG data
        M->>IO: REST: {POST} completePairing(ecgData, nonceSignature)
        IO-)RD: REDIS: Verify challenge exists(challengeId)
        alt challenge present
            RD--)IO: REDIS: OK (CREATED)
            IO-)PG: JDBC: SELECT ecg_ref_data(userId)
            alt ecg reference data exist
                PG--)IO: JDBC: Response
                IO->>RD: REDIS: Update status(challengeId, status="PENDING")
                IO->>KF: KAFKA: PredictRequest(payload)
                KF->>MA: KAFKA: PredictRequest(payload)
                MA->>KF: KAFKA: PredictResponse(TRUE/FALSE)
                KF->>IO: KAFKA: PredictResponse(TRUE/FALSE)
                IO->>RD: REDIS: Update status(challengeId=APPROVED/DENIED)
                loop Poll until timIOut or status != PENDING
                    IO->>RD: REDIS: Read status(challengeId)
                    RD-->>IO: REDIS: status (PENDING/APPROVED/DENIED)
                end
                IO->>M: REST: status(APPROVED/DENIED)
            else
                PG--)IO: JDBC: Response
                IO-->>M: REST: Error: ecg reference data not found
            end
        else missing/expired
            RD-->>IO: REDIS: NOT FOUND/EXPIRED
            IO-->>M: REST: Error: invalid challenge
        end 

        loop Poll until timIOut or status != PENDING
                KC->>IO: REST: {GET} getChallengeStatus(id)
                IO->>RD: REDIS: Read status(challengeId)
                RD-->>IO: REDIS: status (PENDING/APPROVED/DENIED)
                IO-->>KC: REST: StatusResponse
        end

        alt status == APPROVED
            KC-->>U: Login success
        else timIOut or status == DENIED
            KC-->>U: Login failed
        end
        end
    end