sequenceDiagram
    autonumber
    actor U as User
    participant W as WearOS App
    participant M as Mobile App
    participant KC as Tenant System
    participant IO as Orchestrator
    participant PG as Postgres
    participant RD as Redis


    U->>KC: Open registration page
    KC->>IO: REST: {POST} createPairing

    IO-)PG: JDBC: SELECT app_user(userId, tenantId)
    alt user already exists 
        PG--)IO: JDBC: Response
        IO-->>KC: REST: Error: user already exists
        KC-->>U: Registration failed (user exists)
    else user doesn't exist yet
        PG--)IO: JDBC: Response
        IO->>RD: Create pairing(tenantId, userId, jti, status="CREATED", reason="FLOW_CREATED")
        IO->>KC: REST: PairingCreatedResponse(pairingId)
        KC-->>U: Show pairing QR code
        U->>M: Scan pairing QR code
        M->>IO: REST: {POST} initPairing
        IO->>RD: REDIS: Get pairing(pairingId)
        alt pairing not found, expired or already initalized
            RD->>IO: REDIS: Response
            IO-->>M: REST: Error: invalid pairing
            M-->>U: Pairing failed
        else pairing present
            RD->>IO: REDIS: Response
            IO->>RD: REDIS: Update pairing(pairingId, deviceInfo, status="PENDING", reason="FLOW_INITIALIZED_ON_MOBILE_DEVICE")
            IO-->>M: REST: PairingInitializedResponse(nonce, expiryTime)
            M->>W: DATALAYER: Request ECG measurement(challengeId)
            W->>U: Prompt: "Start ECG measurement"
            U-->>W: User performs ECG measurement
            W-->>M: DATALAYER: ECG data
            M->>IO: REST: {POST} completePairing(ecgData, nonceSignature)
            IO-)RD: REDIS: Get pairing(pairingId)
            alt pairing not found, expired, already completed, is not pending or doesn't match the tenant
                RD->>IO: REDIS: Response
                IO-->>M: REST: Error: invalid pairing
                M-->>U: Pairing failed
            else pairing present
                RD->>IO: REDIS: Response
                IO->>PG: JDBC: INSERT INTO app_user(userId, tenantId, deviceInfo)
                IO->>RD: REDIS: Update pairing(pairingId, status="APPROVED", reason="FLOW_COMPLETED_SUCCESSFULLY")

                loop Poll until timeout or (status != PENDING and status != CREATED)
                    KC->>IO: REST: {GET} getPairingStatus(pairingId)
                    IO->>RD: REDIS: Get pairing(pairingId)
                    RD-->>IO: REDIS: Response
                    IO-->>KC: REST: PairingStatusResponse
                end
            end

            alt status == APPROVED
                KC-->>U: Login success
            else timeout, status == DENIED or status==EXPIRED
                KC-->>U: Login failed
            end
        end
    end